# Generated by Django 2.2.12 on 2020-05-19 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='Sport', max_length=100)),
                ('c_iconId', models.IntegerField(default=57392)),
                ('c_fontFamily', models.CharField(default='MaterialIcons', max_length=100)),
                ('c_fontPackage', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(default='Event', max_length=30)),
                ('subtitle', models.CharField(default='No subtitle', max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(default='No address', max_length=50)),
                ('act_people', models.IntegerField(default=0)),
                ('all_people', models.IntegerField(default=0)),
                ('description', models.CharField(default='No description', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
