# Generated by Django 2.2.12 on 2020-05-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Event', max_length=30)),
                ('subtitle', models.CharField(default='No subtitle', max_length=50)),
                ('date', models.CharField(default='No date', max_length=10)),
                ('time', models.CharField(default='No time', max_length=10)),
                ('address', models.CharField(default='No address', max_length=50)),
                ('act_people', models.IntegerField(max_length=3)),
                ('all_people', models.IntegerField(max_length=999)),
                ('description', models.CharField(default='No description', max_length=100)),
            ],
        ),
    ]
