# Generated by Django 2.2.12 on 2020-05-15 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
