# Generated by Django 2.2.12 on 2020-05-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='act_people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='all_people',
            field=models.IntegerField(),
        ),
    ]
