# Generated by Django 2.2.12 on 2020-05-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200510_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='act_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='all_people',
            field=models.IntegerField(default=0),
        ),
    ]
