# Generated by Django 2.2.12 on 2020-05-11 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200511_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_finished',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 11)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(23, 8, 42, 308855)),
        ),
    ]
