# Generated by Django 2.2.12 on 2020-05-11 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200511_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(23, 11, 16, 655521)),
        ),
    ]
