# Generated by Django 2.2.12 on 2020-05-22 00:07

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='act_people',
            field=djongo.models.fields.ListField(null=True),
        ),
    ]
