# Generated by Django 2.2.12 on 2020-05-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200521_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='iconId',
            field=models.IntegerField(default=58411),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Jeux-video', max_length=100),
        ),
    ]
