# Generated by Django 2.2.12 on 2020-05-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200521_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='iconId',
            field=models.IntegerField(default=58168),
        ),
    ]
